// <auto-generated />
using System;
using Heindall_API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Heindall_API.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20230411230320_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Heindall_API.Models.Grupo", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("GrupoArea")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoDescription")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("GrupoMetodo")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoName")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoPassword")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoPort")
                        .HasColumnType("int");

                    b.Property<string>("GrupoType")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoURL")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoUser")
                        .HasColumnType("longtext");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Heindall_API.Models.Integrador", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<long?>("GrupoId1")
                        .HasColumnType("bigint");

                    b.Property<string>("GrupoPassword")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoPort")
                        .HasColumnType("int");

                    b.Property<string>("GrupoUser")
                        .HasColumnType("longtext");

                    b.Property<int>("IntegradorId")
                        .HasColumnType("int");

                    b.Property<string>("IntegradorNome")
                        .HasColumnType("longtext");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("longtext");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId1");

                    b.ToTable("Integradores");
                });

            modelBuilder.Entity("Heindall_API.Models.IntegradorDoUsuario", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("IntegradorId")
                        .HasColumnType("int");

                    b.Property<long?>("IntegradorId1")
                        .HasColumnType("bigint");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<long?>("UsuarioId1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntegradorId1");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("IntegradoresdoUsuario");
                });

            modelBuilder.Entity("Heindall_API.Models.Meta", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Demanda")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("Date");

                    b.Property<string>("Pendencia")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Prioridade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Projeto")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Start")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Heindall_API.Models.Usuario", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("UsuarioBancoDestino")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioCNPJ")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioIDAgencia")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioName")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioNivel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("IntegradorUsuario", b =>
                {
                    b.Property<long>("IntegradoresId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuariosId")
                        .HasColumnType("bigint");

                    b.HasKey("IntegradoresId", "UsuariosId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("IntegradorUsuario");
                });

            modelBuilder.Entity("Heindall_API.Models.Integrador", b =>
                {
                    b.HasOne("Heindall_API.Models.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId1");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Heindall_API.Models.IntegradorDoUsuario", b =>
                {
                    b.HasOne("Heindall_API.Models.Integrador", "Integrador")
                        .WithMany()
                        .HasForeignKey("IntegradorId1");

                    b.HasOne("Heindall_API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Integrador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IntegradorUsuario", b =>
                {
                    b.HasOne("Heindall_API.Models.Integrador", null)
                        .WithMany()
                        .HasForeignKey("IntegradoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Heindall_API.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
